### ISSUE TITLE
Feature request: more flexible diff command

### ISSUE THREAD

**Issue by dangh** [nexional/CompareBuff#2]
Hi, I would like to propose to change `external_tool_path` to something like:

```json
{
  "diff_command": ["cmd", "arg1", "arg2", "$1", "$2", "$3"]
}
```

It yields two benefits:
- We can feed the buffer at any place in the command. Sometime the external tool require additional flag before the filename. For example: `diff --file1 before.json --file2 after.json`
- We can look for how many `$num` argument in the command and show the buffer selector multiple time. It help in case we want 3-way merging for example.

We can extend the toolkit with multiple diff commands:

```json
{
  "diff_commands": [
    {
      "name": "Diff with VS Code",
      "command": ["code", "--diff", "$1", "$2"]
    },
    {
      "name": "3-way Merge with VS Code",
      "command": ["code", "--diff", "$1", "$2", "$3"]
    }
  ]
}
```

I'm not sure if it's feasible as the command name is generate dynamically at run time.

**Comment by nexional** [comment]
Sending more than 2 buffers to tool is not inherently possible at the moment. I'll have to look into it.
For now I released v0.2.14 which will allow custom arguments to external_tool_path (placeholders for 2 buffers {0}, {1}):
e.g. "external_tool_path": [ "C:\\Program Files\\Beyond Compare 4\\BCompare.exe", "--file1", "{0}", "--file2", "{1}" ],
Try it out & let me know.

**Comment by dangh** [comment]
@nexional I got this error in the latest version

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 308, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
reloading plugin Default.side_bar
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1692, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/t/Library/Application Support/Sublime Text/Installed Packages/CompareBuff.sublime-package/compare_buff.py", line 247
SyntaxError: can use starred expression only as assignment target
```

Edit: Found it. we need [_.python-version_](https://www.sublimetext.com/docs/api_environments.html#selecting-the-python-version) file

**Comment by nexional** [comment]
yeah saw that, somehow ST is trying to compile using python 3.3. I downgraded the code now to work with 3.3. Try out v0.2.15.

> we need [.python-version](https://www.sublimetext.com/docs/api_environments.html#selecting-the-python-version) file
Didn't realize we could do that. I'll also add that file.

**Comment by dangh** [comment]
It's working now 🥳

Thank you @nexional

**Comment by nexional** [comment]
For the merge can you try this repo I staged on **gitlab**: https://gitlab.com/vikasera/CompareBuff.git
You can either do "Add Repository" & add this url or directly push the zip in User "Installed Packages" directory.
Once installed use the command `CompareBuff: merge with...` from Command Palette and select two buffers one by one (unlike compare command where you only select one). Once second buffer is selected it'll send all three buffers to the tool in this order -> current one, first_selection, second_selection.
I didn't test is fully so try out all the scenarios you can think of :)
